
# Faviconï¼ˆç½‘ç«™å›¾æ ‡ï¼‰
favicon: /assets/favicon.jpeg

# ä¸»é¡µå¤§å›¾
index_img: https://pic1.zhimg.com/v2-e0ca937a1d3296e7463aa0aa096bef48_r.jpg
default_top_img: https://pic1.zhimg.com/v2-e0ca937a1d3296e7463aa0aa096bef48_r.jpg

nav:
  logo: /assets/favicon.jpeg
  display_title: false
  fixed: true # fixed navigation bar

menu:
  é¦–é¡µ: / || fas fa-home
  å…³äº: https://github.com/xiaorui-23 || fas fa-eject

search:
  path: search.xml
  field: post # post:æ–‡ç« èŒƒå›´ã€page:é¡µé¢èŒƒå›´ã€all:è¦†ç›–æ‰€æœ‰
  content: true # å†…å®¹æ˜¯å¦åŒ…å«æ¯ä¸€ç¯‡æ–‡ç« çš„å…¨éƒ¨å†…å®¹
  template: ./search.xml # ./search.xml æŒ‡å®šå®šåˆ¶çš„XMLæ¨¡æ¿ 

# å¼€å¯æœ¬åœ°æœç´¢
local_search:
  enable: true

hr_icon:
  enable: true
  icon: '\f197' # the unicode value of Font Awesome icon
  icon-top: -10px

# å¤´åƒ 
avatar: 
  img: /assets/WechatIMG1.jpeg
  effect: false

# ç¤¾äº¤å›¾æ ‡
social:
  fab fa-github: https://github.com/xiaorui-23 || Github || "#1989fa"
  fas fa-envelope: mailto:3399251596@qq.com || QQEmail || "#1989fa"
  fab fa-weixin: https://raw.githubusercontent.com/xiaorui-23/xiaorui-23/master/Wechat.jpeg || WeChat || "#00c4b6"

   
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

highlight_copy:  true

code_word_wrap:  true

toc:
  enable: true
  number: true
  auto_open: true # auto open the sidebar

# Related Articles
related_post:
  enable: true
  # limit: 6 # Number of posts displayed  æ˜¾ç¤ºçš„æ–‡ç« æ•°
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸé¡¯ç¤ºå‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

# ä¾§è¾¹æ 
# --------------------------------------
aside:
  enable: true
  mobile: true # display on mobile
  position: left # left or right 
  card_tags color: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      description: å°ç‘çš„ä¸ªäººåšå®¢å•¦ã€‚
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/xiaorui-23
  card_announcement:
    enable: true
    content: å°ç‘çš„ä¸ªäººä¸»é¡µåšå®¢ä¸Šçº¿å•¦ğŸ‰ğŸ‰ğŸ‰ã€‚æ¬¢è¿è®¿é—®æœ¬ç«™ã€‚æ„Ÿè§‰ä¸é”™çš„è¯å¯ä»¥ ctrl/command + d è¿›è¡Œæ”¶è—å“¦

# å¤åˆ¶è‡ªåŠ¨è¿½åŠ ç‰ˆæƒ
# copy settings
# copyright: Add the copyright information after copied content (è¤‡è£½çš„å…§å®¹å¾Œé¢åŠ ä¸Šç‰ˆæ¬Šä¿¡æ¯)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50



# è¨ªå•äººæ•¸
busuanzi:
  site_uv: false
  site_pv: false
  page_pv: true

runtimeshow:
  enable: true
  publish_date: 4/27/2023 00:00:00
  #æ ¼å¼: æœˆ/æ—¥/å¹´ æ™‚é–“
  #ä¹Ÿå¯ä»¥ å¹´/æœˆ/æ—¥ æ™‚é–“

# CDN:
#   option:
#   	busuanzi: busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js


# Footer Settings
# --------------------------------------
footer:
  owner:
    enable: true
    since: 2023
  copyright: false
  custom_text: <a href="https://beian.miit.gov.cn/"><span>èœ€ICPå¤‡2021027422å·-1</span></a>
    
    